### ISSUE TITLE
server address fails with piped address list

### ISSUE THREAD

**Issue by rgreen83** [LabtechConsulting/LabTech-Powershell-Module#1]
For those with piped server address lists in the registry from the labtech template the reinstall and possibly other functions will fail as they can't use the pipe delimited string. something like this should work but I couldn't get it working

line 542  `[string]$Server = (Get-LTServiceInfo).'Server Address' -split "|",0,"SimpleMatch" | select -First 1 ,`

That split code works when using the get-ltserviceinfo cmdlet directly, just not from the reinstall cmdlet

**Comment by LabtechConsulting** [comment]
I have updated the module to address this.
((Get-LTServiceInfo).'Server Address'.Split('|'))[0].trim()
