### ISSUE TITLE
Date conversion not working outside of US Date Formats - Breaks Command

### ISSUE THREAD

**Issue by gavsto** [LabtechConsulting/LabTech-Powershell-Module#38]
https://github.com/LabtechConsulting/LabTech-Powershell-Module/blob/8618eec2d4f80e31b809974088d2b967c5acdb24/LabTech.psm1#L1784

The date conversion here results in an error on none US systems, IE in the UK where the date format is dd/mm/yyyy:

`Get-LTError : ERROR: There was an error reading the log. Cannot convert value "15/11/2018 08:30:59" to type
"System.DateTime". Error: "String was not recognized as a valid DateTime."`

**Comment by DarrenWhite99** [comment]
I pushed an update into the Get-LTError and Get-LTProbeError that should make date handling better. Please confirm it works for you and I'll submit a pull request for the main branch.
[https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/Get-LTServiceInfo-Update/LabTech.psm1](https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/Get-LTServiceInfo-Update/LabTech.psm1)

**Comment by gavsto** [comment]
@DarrenWhite99 that fixed the issue - sorts the LT log as it should via date correctly too! Thanks
