### ISSUE TITLE
.NET 3.5 Install Check Error Handling

### ISSUE THREAD

**Issue by johnsalle** [LabtechConsulting/LabTech-Powershell-Module#4]
In the Install-LTService function, you do a check to see if .NET 3.5 is installed and attempt to install it. In the error handling for that .NET 3.5 installation, you do the following. (Currently lines 491-495)

Else{
                Write-Output "ERROR: .NET 3.5 install failed."
                Write-Output $Result
                Exit
            } 

The problem is, if I'm manually running the Install-LTService function and not using a script, having it output the error code and then immediately exit will flash too fast to understand what's happening before it closes the window. I think having a pause or a break would be more effective.

I think I read that "exit" behaves differently on different versions of PowerShell. I don't recall exactly what OS or PoSh version I found this bug on, sorry.

**Comment by LabtechConsulting** [comment]
Replaced EXIT's in favor of breaks.
