### ISSUE TITLE
Reset-LTService removes the location ID by mistake

### ISSUE THREAD

**Issue by tonypags** [LabtechConsulting/LabTech-Powershell-Module#47]
The issue: 
The command `Reset-LTService -ID -Mac` is not supposed to remove the location ID. But it does. 

To reproduce: 
```
C:\Windows\LTSvc>"%windir%\System32\WindowsPowerShell\v1.0\powershell.exe" -noprofile -command "& {(new-object Net.WebCl
ient).DownloadString('http://bit.ly/ltposh') | iex; Reset-LTService -ID -Mac}"
OLD ID: 5374 LocationID: 291 MAC: 00059A3C7A00
Waiting for Services to Stop.........
Services Stopped successfully.
.Removing ID
.Removing LocationID    <-- NOOOO!!!!!!!!!!
.Removing MAC
Waiting for Services to Start..
Services Started successfully.
...
```

The fix: Line 1922
`If (!($ID -and $LocationID -and $MAC)){`
should be
`If (!($ID -and $Location -and $MAC)){`

:)

**Comment by DarrenWhite99** [comment]
Pull Request https://github.com/LabtechConsulting/LabTech-Powershell-Module/pull/48 includes updates which should fix this. They should be committed soon, pending review.

**Comment by DarrenWhite99** [comment]
This should be fixed now.  Also make sure that you are using the CORRECT bit.ly link:
https://bit.ly/LTPoSh

**Comment by DarrenWhite99** [comment]
Reviewed function, confirmed changes resolve the reported issue.
