### ISSUE TITLE
Hide/Show-LTAddRemove

### ISSUE THREAD

**Issue by ChrisTaylorRocks** [LabtechConsulting/LabTech-Powershell-Module#5]
There are new keys with 11

HKEY_CLASSES_ROOT\Installer\Products\D1003A85576B76D45A1AF09A0FC87FAC
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\D1003A85576B76D45A1AF09A0FC87FAC
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Products\D1003A85576B76D45A1AF09A0FC87FAC\InstallProperties
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{58A3001D-B675-4D67-A5A1-0FA9F08CF7CA}

**Comment by ChrisTaylorRocks** [comment]
Also add those keys to uninstaller.

**Comment by LabtechConsulting** [comment]
Also see decompiled uninstaller.
https://gist.github.com/jesseconnr/e9b8c31a81f9df793bfc01dcaea5f342

**Comment by LabtechConsulting** [comment]
Need to update the exported reg keys for show to be current for the LT 11 agent.
