### ISSUE TITLE
64-bit OS Detection causing script to fail on ARM processors (Surface Pro X)

### ISSUE THREAD

**Issue by elevatejoe** [LabtechConsulting/LabTech-Powershell-Module#52]
When you try to run the "(new-object Net.WebClient).DownloadString('https://bit.ly/LTPoSh') | iex;" command on a Surface Pro X (64-bit custom ARM CPU), it tries to switch to 64-bit PowerShell and creates an endless loop of spawned Powershell.exe processes. 

Output looks like:
```
PS C:\windows\system32> (new-object Net.WebClient).DownloadString('https://bit.ly/LTPoSh') | iex;
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
```

https://oofhours.com/2020/02/04/powershell-on-windows-10-arm64/ this site indicates that 64-bit tests should exclude the ARM processor architecture to avoid these issues.

**Comment by DarrenWhite99** [comment]
Please test the branch at https://github.com/DarrenWhite99/LabTech-Powershell-Module/tree/ARM64-Dev .  Once we can verify that it works (without looping at least) under ARM64 I will complete the pull and bring the fixes to the main branch here.

**Comment by elevatejoe** [comment]
Running unmodified, it still seems to loop, but now when I kill it at least the processes clean up without a task kill.
`PS C:\windows\system32> (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/LabtechConsulting/LabTech-Powershell-Module/4db32d746a3c1253eaa6cebbc7f834c402164a0e/LabTech.psm1') | iex
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.`

Copied into ISE and ran it, same results. When I change line 53 from Write-Debug to Write-Warning, I get:

`WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
WARNING: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
Program 'powershell.exe' failed to run: The filename or extension is too longAt line:131 char:9
+         &"$pshell" -NonInteractive -NoProfile $myInvocation.MyCommand
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:131 char:9
+         &"$pshell" -NonInteractive -NoProfile $myInvocation.MyCommand
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
 
WARNING: Exiting 64-bit session. Module will only remain loaded in native 64-bit PowerShell environment.`
And then a script break/exit. I tested enabling long paths in the registry and rebooting, but that had no effect.

If I change line 49 to:
`If ($env:PROCESSOR_ARCHITEW6432 -match '64' -and [IntPtr]::Size -ne 8 -and $env:PROCESSOR_ARCHITEW6432 -ne 'ARM64')`

It runs without error and I was able to execute the functions.

**Comment by DarrenWhite99** [comment]
To get more information on the choices is it making, try this:
powershell.exe "$DebugPreference=$VerbosePreference='Continue'; iex (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/ARM64-Dev/LabTech.psm1'); Get-LTServiceInfo"

**Comment by elevatejoe** [comment]
`$DebugPreference='Continue'; (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/ARM64-Dev/LabTech.psm1') | iex; Get-LTServiceInfo`

Results in an endless loop and a bunch of stuck processes:

> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit access.
> DEBUG: Loading WOW64Redirection functions
>

**Comment by elevatejoe** [comment]
I was able to run Install-LTService and Get-LTServiceInfo without any issues. Reinstall-LTservice seems to have an issue, but I tested and it is not specific to ARM.

> PS C:\windows\system32> $DebugPreference='Continue'; (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/ARM64-Dev/LabTech.psm1') | iex; Get-LTServiceInfo                     
> 
> WARNING: 32-bit PowerShell session detected on 64-bit OS. Attempting to launch 64-Bit session to process commands.
> DEBUG: SYSNATIVE PATH REDIRECTION IS NOT AVAILABLE. Attempting to disable System32 path redirection for native 64bit
> access.
> DEBUG: Loading WOW64Redirection functions
> DEBUG: Native 64-bit PowerShell environment unavailable in ARM64. Execution will continue.
> DEBUG: Starting Get-LTProxy at line 3652
> DEBUG: Line 3143: Decoding Server Password.
> DEBUG: Line 3226: Attempting Decode for '{sanitized}' with Key 'Thank you for using LabTech.'
> DEBUG: Line 3146: Decoding Agent Password.
> DEBUG: Line 3226: Attempting Decode for
> '{sanitized}' with Key '{sanitized}'
> DEBUG: Line 3226: Attempting Decode for
> '{sanitized}' with Key 'Thank you for
> using LabTech.'
> DEBUG: Line 3226: Attempting Decode for
> '{sanitized}' with Key ''
> DEBUG: Line 3266: Failed to Decode string:
> '{sanitized}'
> DEBUG: Line 3266: Failed to Decode string:
> '{sanitized}'
> DEBUG: Line 3266: Failed to Decode string:
> '{sanitized}'
> DEBUG: Line 3668: Setting ProxyServerURL to
> DEBUG: Line 3676: Setting ProxyUsername to
> DEBUG: Line 3683: Setting ProxyPassword to
> DEBUG: Exiting Get-LTProxy at line 3697
> DEBUG: Starting Get-LTServiceInfo at line 212
> DEBUG: Exiting Get-LTServiceInfo at line 255
> 
> 
> ProductCode            : {sanitized}
> LocationID             : 1
> Server Address         : https://{sanitized}
> TrayPort               : 42000
> VNCServiceName         : LabVNC
> DefaultTempPath        : C:\windows\Temp
> BasePath               : C:\windows\LTsvc
> FullSystemFunction     : False
