### ISSUE TITLE
ReInstall-LTService function fails to install

### ISSUE THREAD

**Issue by elevatejoe** [LabtechConsulting/LabTech-Powershell-Module#54]
ReInstall-LTservice command completes the Uninstall, then starts the Install, but it calls a different URL than the Install-LTService command - it looks to be the old deprecated probe URL and thus fails to download the installer. 

> DEBUG: Starting Reinstall-ltservice at line 1593
> DEBUG: Starting Get-LTServiceInfo at line 212
> DEBUG: Exiting Get-LTServiceInfo at line 255
> Reinstalling LabTech with the following information, -Server https://{sanitized},https://{sanitized}  -LocationID 1
> 
> DEBUG: Starting Uninstall-LTService at line 684
> DEBUG: Line 780: Testing Server Response and Version: https://{sanitized}/LabTech/Agent.aspx
> DEBUG: Line 783: Raw Response: ||||||200.278
> DEBUG: Line 805: Downloading RemoteAgent.msi from **https://{sanitized}/LabTech/Service/LabTechRemoteAgent.msi**
> DEBUG: Line 842: Downloading Agent_Uninstall.exe from https://{sanitized}/LabTech/Service/LabUninstall.exe
> DEBUG: Line 869: Server https://{sanitized} has been selected.
> Starting Uninstall.
> DEBUG: Starting Stop-LTService at line 409
> DEBUG: Line 3093: Sending service command 'Kill VNC' (141) to 'LTService'
> DEBUG: Line 3093: Sending service command 'Kill Trays' (142) to 'LTService'
> Waiting for Services to Stop.....
> Services Stopped successfully.
> DEBUG: Exiting Stop-LTService at line 463
> DEBUG: Line 888: Terminating Process LTSVC
> DEBUG: Line 896: Executing Command "regsvr32.exe /u C:\Windows\LTsvc\wodVPN.dll /s"
> DEBUG: Line 906: Executing Command "msiexec.exe /x "C:\Windows\Temp\RemoteAgent.msi" /qn"
> DEBUG: Line 918: Executing Command "C:\Windows\Temp\Agent_Uninstall.exe"
> DEBUG: Line 957: Found Registry Key: Registry::HKEY_CURRENT_USER\SOFTWARE\LabTech\Service
> DEBUG: Line 957: Found Registry Key: Registry::HKEY_CURRENT_USER\SOFTWARE\LabTech\LabVNC
> LabTech has been successfully uninstalled.
> DEBUG: Exiting Uninstall-LTService at line 996
> DEBUG: Starting Install-LTService at line 1142
> DEBUG: Line 1250: Testing Server Response and Version: https://{sanitized}/LabTech/Agent.aspx
> DEBUG: Line 1252: Raw Response: ||||||200.278
> DEBUG: Line 1288: Downloading Agent_Install.msi from **https://{sanitized}/LabTech/Deployment.aspx?Probe=1&installType=msi&MSILocations=1**
> WARNING: WARNING: Line 1308: Error encountered downloading from https://{sanitized}.
> DEBUG: Line 1250: Testing Server Response and Version: https://{sanitized}/LabTech/Agent.aspx
> DEBUG: Line 1252: Raw Response: ||||||200.278
> DEBUG: Line 1288: Downloading Agent_Install.msi from **https://{sanitized}/LabTech/Deployment.aspx?Probe=1&installType=msi&MSILocations=1**
> WARNING: WARNING: Line 1308: Error encountered downloading from https://{sanitized}.
> Install-LTService : ERROR: Line 1474: No valid server was reached to use for the install.
> DEBUG: Exiting Install-LTService at line 1476
> DEBUG: Exiting Reinstall-ltservice at line 1697

Install-LTService output:

> Install-LTService -server https://{sanitized} -Password '{sanitized}' -SkipDotNet
> DEBUG: Starting Install-LTService at line 1142
> DEBUG: Line 1250: Testing Server Response and Version: https://{sanitized}/LabTech/Agent.aspx
> DEBUG: Line 1252: Raw Response: ||||||200.278
> DEBUG: Line 1288: Downloading Agent_Install.msi from **https://{sanitized}/LabTech/Service/LabTechRemoteAgent.msi**
> DEBUG: Starting Test-LTPorts at line 2487
> DEBUG: Exiting Test-LTPorts at line 2566
> Starting Install.
> Waiting for agent to register..........
> DEBUG: Starting Get-LTProxy at line 3652
> DEBUG: Line 3143: Decoding Server Password.
> DEBUG: Line 3226: Attempting Decode for '{sanitized}' with Key 'Thank you for using LabTech.'
> DEBUG: Line 3146: Decoding Agent Password.
> DEBUG: Line 3226: Attempting Decode for '{sanitized}' with Key '{sanitized}'
> DEBUG: Line 3226: Attempting Decode for '{sanitized}' with Key 'Thank you for using LabTech.'
> DEBUG: Line 3226: Attempting Decode for '{sanitized}' with Key ''
> DEBUG: Line 3266: Failed to Decode string: '{sanitized}'
> DEBUG: Line 3266: Failed to Decode string: '{sanitized}'
> DEBUG: Line 3266: Failed to Decode string: '{sanitized}'
> DEBUG: Line 3668: Setting ProxyServerURL to
> DEBUG: Line 3676: Setting ProxyUsername to
> DEBUG: Line 3683: Setting ProxyPassword to
> DEBUG: Exiting Get-LTProxy at line 3697
> LabTech has been installed successfully. Agent ID: 3299 LocationID: 1
> DEBUG: Exiting Install-LTService at line 1476

**Comment by DarrenWhite99** [comment]
It looks like Redo-LTService isn't passing the server password to Install-LTService...   But the Verbose output is missing, which would have been helpful in reporting what it was doing.   Debug output doesn't replace Verbose, it just adds more.  To get all the troubleshooting output $VerbosePreference needs to be set as well as $DebugPrefrerence.

**Comment by DarrenWhite99** [comment]
Try any tests you like against this branch:
`powershell.exe "$DebugPreference=$VerbosePreference='Continue'; iex (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/CurrentDevelopment/LabTech.psm1'); Get-LTServiceInfo"`

**Comment by elevatejoe** [comment]
`powershell.exe "$DebugPreference=$VerbosePreference='Continue'; iex (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/CurrentDevelopment/LabTech.psm1'); ReInstall-LTService -SkipDotNet"`

Output:

> DEBUG: Starting Get-LTProxy at line 3586
> VERBOSE: Discovering Proxy Settings used by the LT Agent.
> DEBUG: Line 3077: Decoding Server Password.
> DEBUG: Line 3160: Attempting Decode for '{sanitized}' with Key 'Thank you for using LabTech.'
> DEBUG: Line 3080: Decoding Agent Password.
> DEBUG: Line 3160: Attempting Decode for '{sanitized}' with Key '{sanitized}'
> DEBUG: Line 3160: Attempting Decode for '{sanitized}' with Key 'Thank you for using LabTech.'
> DEBUG: Line 3160: Attempting Decode for '{sanitized}' with Key ''
> DEBUG: Line 3200: Failed to Decode string: '{sanitized}'
> DEBUG: Line 3200: Failed to Decode string: '{sanitized}'
> DEBUG: Line 3200: Failed to Decode string: '{sanitized}'
> DEBUG: Line 3602: Setting ProxyServerURL to
> DEBUG: Line 3610: Setting ProxyUsername to
> DEBUG: Line 3617: Setting ProxyPassword to
> DEBUG: Exiting Get-LTProxy at line 3631
> DEBUG: Starting ReInstall-LTService at line 1527
> DEBUG: Starting Get-LTServiceInfo at line 146
> DEBUG: Exiting Get-LTServiceInfo at line 189
> Reinstalling LabTech with the following information, -Server https://{sanitized}  -LocationID 1
> VERBOSE: Starting: Uninstall-LTService -Server https://{sanitized}
> DEBUG: Starting Uninstall-LTService at line 618
> DEBUG: Line 714: Testing Server Response and Version: https://{sanitized}/LabTech/Agent.aspx
> DEBUG: Line 717: Raw Response: ||||||200.278
> DEBUG: Line 739: Downloading RemoteAgent.msi from https://{sanitized}/LabTech/Service/LabTechRemoteAgent.msi
> DEBUG: Line 776: Downloading Agent_Uninstall.exe from https://{sanitized}/LabTech/Service/LabUninstall.exe
> VERBOSE: Successfully downloaded files from https://{sanitized}.
> Starting Uninstall.
> DEBUG: Starting Stop-LTService at line 343
> DEBUG: Line 3027: Sending service command 'Kill VNC' (141) to 'LTService'
> DEBUG: Line 3027: Sending service command 'Kill Trays' (142) to 'LTService'
> VERBOSE: Stopping Labtech Services
> Waiting for Services to Stop.........
> Services Stopped successfully.
> DEBUG: Exiting Stop-LTService at line 397
> VERBOSE: Terminating LabTech Processes from C:\Windows\LTsvc if found running: 
> LSR.exe LTSVC.exe LTSvcMon.exe LTTray.exe PS.exe setcad.exe tvnserver.exe
> DEBUG: Line 830: Executing Command "regsvr32.exe /u C:\Windows\LTsvc\wodVPN.dll /s"
> VERBOSE: Launching MSI Uninstall.
> DEBUG: Line 840: Executing Command "msiexec.exe /x "C:\Windows\Temp\RemoteAgent.msi" /qn"
> VERBOSE: Launching Agent Uninstaller
> DEBUG: Line 852: Executing Command "C:\Windows\Temp\Agent_Uninstall.exe"
> VERBOSE: Removing Services if found.
> VERBOSE: Cleaning Files remaining if found.
> VERBOSE: Cleaning Registry Keys if found.
> DEBUG: Line 891: Found Registry Key:
> Registry::HKEY_CURRENT_USER\SOFTWARE\LabTech\Service
> LabTech has been successfully uninstalled.
> DEBUG: Exiting Uninstall-LTService at line 930
> VERBOSE: Waiting 20 seconds for prior uninstall to settle before starting Install.
> VERBOSE: Starting: Install-LTService -Server https://{sanitized} -LocationID 1 -Hide:$False
> DEBUG: Starting Install-LTService at line 1076
> DEBUG: Line 1184: Testing Server Response and Version: https://{sanitized}/LabTech/Agent.aspx
> DEBUG: Line 1186: Raw Response: ||||||200.278
> Install-LTService : Anonymous downloads are not allowed. ServerPassword or InstallerToken may be needed.
> At line:1618 char:17
>  ...             Install-LTService -Server $ServerList -ServerPassword $Se ...
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>      FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-LTService
> 
> Install-LTService : ERROR: Line 1408: No valid server was reached to use for the install.
> At line:1618 char:17
>  ...             Install-LTService -Server $ServerList -ServerPassword $Se ...
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
>    tion
>      FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-LTService
> 
> DEBUG: Exiting Install-LTService at line 1410
> DEBUG: Exiting ReInstall-LTService at line 1631

**Comment by DarrenWhite99** [comment]
I see when you ran Install-LTService, you provided a password

> `Install-LTService -server https://{sanitized} -Password '{sanitized}' -SkipDotNet`

But the Reinstall-LTService does not appear to have had a password provided.

> `powershell.exe "$DebugPreference=$VerbosePreference='Continue'; iex (new-object Net.WebClient).DownloadString('https://raw.githubusercontent.com/DarrenWhite99/LabTech-Powershell-Module/CurrentDevelopment/LabTech.psm1'); ReInstall-LTService -SkipDotNet"`

I tested with a password provided and the reinstall was successful. 
`ReInstall-LTService -SkipDotNet -Password 'xxxxx'`

I have merged the changes from my CurrentDevelopment branch to the LabtechConsulting master branch (#55) so this issue should be resolved.
