### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by DesAWSume** [LabtechConsulting/LabTech-Powershell-Module#60]
Reinstall module from this is not allowing me to reinstall the LT agent 

Error: 
Could not create SSL/TLS secure channel

Function that I ran: 
(new-object Net.WebClient).DownloadString('http://bit.ly/LTPoSh') | iex; Reinstall-LTService -Server xxxxxxxx == -LocationID xxxxx

**Comment by NickWhitNTES** [comment]
Same issue, all commands.  Started recently.  TLS Issue?

**Comment by bENLiang** [comment]
Don't think so, as you can https into this link.
Anyone have a solution?

**Comment by bENLiang** [comment]
End up running the script locally, rather than the download string

**Comment by DarrenWhite99** [comment]
Use:
[Net.ServicePointManager]::SecurityProtocol=[enum]::GetValues([Net.SecurityProtocolType])|Where-Object
{$_ -gt [Net.SecurityProtocolType]::Tls}; (new-object
Net.WebClient).DownloadString('http://bit.ly/LTPoSh') | iex;
Reinstall-LTService -Server xxxxxxxx == -LocationID xxxxx

**Comment by DarrenWhite99** [comment]
GitHub is now requiring TLS1.2 for connections, and stock powershell may not have it enabled. You just need to enable TLS1.2 using the command above (Enables all TLS+ versions) or explicitly enable TLS1.2 before pulling from GitHub. (Or host a copy on a server that allows lower security connections).
